name: Publish NPM GitHub Package

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@autograders'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
